---
# Copyright 2017, IBM US, Inc.
#
# Install and setup nfs server 
#

- name: install nfs packages
  shell: "apt-get install -y nfs-common"


- name: init client nfs directories
  set_fact:
     directory: {}

- name: set client nfs directories
  include: append_dir.yml
  with_items: "{{ nfs.nfs_shares }}"

- name: Setup fstab
  lineinfile:
    dest: "/etc/fstab"
    line: "{{ hostvars[groups[nfs.nfs_server][0]]['interconnect_addr'] }}:{{ item.key }} {{ item.value }} nfs auto 0 0"
    insertafter: EOF
  with_dict: "{{ directory }}"

- name: create mount directores
  file: 
    path: "{{ item.value }}"
    state: directory
    mode: 0755
    owner: "{{ userid_default }}"
    group: "{{ userid_default }}"
  with_dict: "{{ directory }}"

- name: mount nfs
  shell: "mount -t nfs {{ hostvars[groups[nfs.nfs_server][0]]['interconnect_addr'] }}:{{ item.key }} {{ item.value }}"
  with_dict: "{{ directory }}"
...
