---
- name: Dump all vars
  template:
    src: "{{ playbook_dir }}/templates/dumpall.j2"
    dest: /tmp/ansible.all

- name: init client nfs directories
  set_fact:
     directory: {} 

- name: set client nfs directories
  include: append_dir.yml
  with_items: "{{ nfs.nfs_shares }}"

- debug: var=directory
- debug: var=directory.keys()

- name: mount nfs
  shell: "echo mount -t nfs {{ hostvars[groups[nfs.nfs_server][0]]['interconnect_addr'] }}:{{ item }}  >> /tmp/dump.out"
  with_items: "{{ nfs.nfs_shares }}"

- name: Setup fstab
  lineinfile:
    dest: "/tmp/junk.out"
    line: "{{ hostvars[groups[nfs.nfs_server][0]]['interconnect_addr'] }}:{{ item.key }} {{ item.value }} nfs auto 0 0"
    insertafter: EOF
  with_dict: "{{ directory }}" 

...
