---
# Copyright 2017, IBM US, Inc.
#
#install libccl and it's depencies
#
- name: Copy ccl debs
  copy: src="{{ reference_architecture['nvidia_playbook']['openblas_deb'] }}" dest="/tmp/openblas.deb"

- name: Install ccl dependencies
  shell: apt-get install -y {{ item }}
  with_items: "{{ reference_architecture['nvidia_playbook']['openblas_deps'] }}"
  become: true
  ignore_errors: yes


- name: Install openblas
  shell: dpkg -i /tmp/openblas.deb
  
...
