---
# Copyright 2016, IBM US, Inc.
#
#gpudb playbook:  Install latest nvidia driver for gpudb.
# eventually there will be more involved steps, however,
# for gpudb's initial purposes, they just need a local
# install of the latest nvidia kernel drivers.
#
#- name: Including caffe-nv playbook 
#  include: caffe-nv_install.yml
#  when: (framework == 'caffe-nv')
#  become: true
#- name: Install openBlas driver
#  include: tasks/install_openblas.yml
#  when: "{{ 'caffe-nv' in hostvars[inventory_hostname]['powerai_frameworks'] }}"

#- name: Install ccl driver
#  include: tasks/install_ccl.yml
#  when: "{{ 'caffe-nv' in hostvars[inventory_hostname]['powerai_frameworks'] }}"
- name: copy mldl repo
  copy: src="{{ reference_architecture['powerai_playbook']['mldl_deb'] }}" dest="/tmp/mldl.deb"

- name: mldl repo
  shell: dpkg -i /tmp/mldl.deb

- name: Refresh package update
  shell: apt-get update

- name: caffe-nv
  include: tasks/install_caffe-nv.yml
  when: "{{ 'caffe-nv' in hostvars[inventory_hostname]['powerai_frameworks'] }}"
  become: true

- name: caffe-bvlc
  include: tasks/install_caffe-bvlc.yml
  when: "{{ 'caffe-bvlc' in hostvars[inventory_hostname]['powerai_frameworks'] }}"
  become: true

- name: caffe-ibm
  include: tasks/install_caffe-ibm.yml
  when: "{{ 'caffe-ibm' in hostvars[inventory_hostname]['powerai_frameworks'] }}"
  become: true

- name: torch
  include: tasks/install_torch.yml
  when: "{{ 'torch' in hostvars[inventory_hostname]['powerai_frameworks'] }}"
  become: true

- name: theano
  include: tasks/install_theano.yml
  when: "{{ 'theano' in hostvars[inventory_hostname]['powerai_frameworks'] }}"
  become: true

- name: digits
  include: tasks/install_digits.yml
  when: "{{ 'digits' in hostvars[inventory_hostname]['powerai_frameworks'] }}"
  become: true

- name: tensorflow
  include: tasks/install_tensorflow.yml
  when: "{{ 'tensorflow' in hostvars[inventory_hostname]['powerai_frameworks'] }}"
  become: true
