---
# Copyright 2016, IBM US, Inc.
#
#gpudb playbook:  Install latest nvidia driver for gpudb.
# eventually there will be more involved steps, however,
# for gpudb's initial purposes, they just need a local
# install of the latest nvidia kernel drivers.
#
- name: Gather facts from localhost
  hosts: localhost
  gather_facts: yes

#- name: dumpall
#  hosts: parameter
#  tasks:
#    - include: tasks/dumpall.yml

- name: Create nfs Server
  hosts: all
  tasks:
    - include: tasks/deploy_nfs_server.yml
      when: "groups.{{ nfs.nfs_server }} is defined and inventory_hostname in groups.{{ nfs.nfs_server }}"

- name: Create nfs Client 
  hosts: all
  tasks:
    - include: tasks/deploy_nfs_client.yml
      when: "groups.{{ nfs.nfs_clients }} is defined and inventory_hostname in groups.{{ nfs.nfs_clients }}"

- name: Install OFED drivers if needed
  hosts: all
  tasks:
    - include: tasks/install_ofed.yml
      when: 
        - networks[item].type is defined and networks[item].type == 'ib'
        - reference_architecture['powerai_playbook']['ofed_driver'] is defined
      with_items: "{{ host_networks.keys() }}"
  handlers:
    - include: handlers/reboot.yml

- name: Install cuda
  hosts: all 
  tasks:
    - include: tasks/install_nvidia.yml
  become: true

- name: Install Frameworks 
  hosts: all
  tasks:
    - name: Framework Install 
      include: framework_install.yml
  become: true

- name: Tensorflow Sample Install
  hosts: all
  tasks:
    - name: Tensorflow samples
      include: tensor_dist_install.yml
  become: true

...
