reference-architecture:
    gpudb_nvidia_playbook:
        description: playbook for installing nvidia for gpudb
        cuda_deb: packages/cuda8.deb
        cudnn5_deb: "packages/cudnn5.deb"
        cudnn5_dev_deb: "packages/cudnn5_dev.deb"
        driver_level: nvidia-361
        dkms_deb: packages/dkms.deb

    powerai_playbook:
        description: Playbook for installing Power machine learning frameworks
        mldl_deb: "packages/mldl.deb"
        mnist_test_src: "static/tensorflow/distributed/samples/mnist/mnist_dist.py"
        mnist_test_dest: "/opt/DL/tensorflow/samples/mnist_dist.py"


ipaddr-mgmt-network: 192.168.3.0/24
ipaddr-mgmt-switch:
    rack1: 192.168.3.5
ipaddr-data-switch:
    rack1: 9.3.3.178
redundant-network: false
userid-default: ubuntu
password-default: passw0rd
userid-mgmt-switch: admin
password-mgmt-switch: admin
userid-data-switch: admin
password-data-switch: admin
networks:
    external:
        description: Organization site or external network
        addr: 9.3.3.0/24
        broadcast: 9.3.3.255
        gateway: 9.3.3.1
        dns-nameservers: 9.3.1.200
        dns-search: aus.stglabs.ibm.com
        method: static
        eth-port: eth10
    interconnect:
        description: Private 10G Data Network to Interconnect Cluster
        addr: 10.0.0.0/24
        broadcast: 10.0.0.255
        method: static
        eth-port: eth11
    mgmt-pxe:
        description: Management Network
        method: dhcp
        eth-port: eth15
node-templates:
    parameter:
        hostname: min
        userid-ipmi: ADMIN
        password-ipmi: admin
        cobbler-profile: ubuntu-16.04.1-server-ppc64el
        os-disk:
        - /dev/sdj
        - /dev/sdi
        name-interfaces:
            mac-pxe: eth15
            mac-eth10: eth10
            mac-eth11: eth11
        ports:
            ipmi:
                rack1:
                - 11
            pxe:
                rack1:
                - 12
            eth10:
                rack1:
                - 7
            eth11:
                rack1:
                - 8
        networks:
        - external
        - interconnect
        - mgmt-pxe
        - mgmt-pxe
    worker:
        hostname: min
        userid-ipmi: ADMIN
        password-ipmi: admin
        cobbler-profile: ubuntu-16.04.1-server-ppc64el
        os-disk:
        - /dev/sdj
        - /dev/sdi
        name-interfaces:
            mac-pxe: eth15
            mac-eth10: eth10
            mac-eth11: eth11
        ports:
            ipmi:
                rack1:
                - 7
                - 9
            pxe:
                rack1:
                - 8
                - 10
            eth10:
                rack1:
                - 3
                - 5
            eth11:
                rack1:
                - 4
                - 6
        networks:
        - external
        - interconnect
        - mgmt-pxe
        - mgmt-pxe
nodes:
    worker:
    -   hostname: min-1
        powerai-frameworks:
        - tensorflow
        userid-ipmi: ADMIN
        password-ipmi: admin
        port-ipmi: 7
        port-pxe: 8
        port-eth10: 3
        port-eth11: 4
        mac-ipmi: 70:e2:84:14:1a:29
        ipv4-ipmi: 192.168.3.101
        rack-id: rack1
        template: worker
        mac-pxe: 70:e2:84:14:1a:2b
        ipv4-pxe: 192.168.3.102
        architecture: ppc64
        chassis-part-number: 8335-GTB
        chassis-serial-number: 10109EA
        external-addr: 9.3.3.2
        interconnect-addr: 10.0.0.1
        mac-eth10: 98:be:94:68:af:84
        mac-eth11: 98:be:94:68:af:85
    -   hostname: min-2
        powerai-frameworks:
        - tensorflow
        userid-ipmi: ADMIN
        password-ipmi: admin
        port-ipmi: 9
        port-pxe: 10
        port-eth10: 5
        port-eth11: 6
        mac-ipmi: 70:e2:84:14:0a:10
        ipv4-ipmi: 192.168.3.103
        rack-id: rack1
        template: worker
        mac-pxe: 70:e2:84:14:0a:12
        ipv4-pxe: 192.168.3.104
        architecture: ppc64
        chassis-part-number: 8335-GTB
        chassis-serial-number: 1004C9A
        external-addr: 9.3.3.3
        interconnect-addr: 10.0.0.2
        mac-eth10: 98:be:94:59:fd:d4
        mac-eth11: 98:be:94:59:fd:d5

    parameter:
    -   hostname: min-3
        powerai-frameworks:
        - tensorflow
        userid-ipmi: ADMIN
        password-ipmi: admin
        port-ipmi: 11
        port-pxe: 12
        port-eth10: 7
        port-eth11: 8
        mac-ipmi: 70:e2:84:14:01:df
        ipv4-ipmi: 192.168.3.105
        rack-id: rack1
        template: parameter
        mac-pxe: 98:be:94:59:fb:12
        ipv4-pxe: 192.168.3.106
        architecture: ppc64
        chassis-part-number: 8335-GTB
        chassis-serial-number: '0000000000000000'
        external-addr: 9.3.3.4
        interconnect-addr: 10.0.0.3
        mac-eth10: 98:be:94:59:fb:10
        mac-eth11: 98:be:94:59:fb:11
switches:
    switches:
        mgmt:
        -   hostname: mgmtswitch1
            ipv4-addr: 192.168.3.5
            rack-id: rack1
            userid: admin
            password: admin
        data:
        -   hostname: dataswitch1
            ipv4-addr: 9.3.3.178
            rack-id: rack1
            userid: admin
            password: admin
