reference-architecture:
    gpudb_nvidia_playbook:
        description: playbook for installing nvidia for gpudb
        cuda_deb: "packages/cuda8.deb"
        cudnn5_deb: "packages/cudnn5.deb"
        cudnn5_dev_deb: "packages/cudnn5_dev.deb"
        driver_level: "nvidia-361"
        dkms_deb: "packages/dkms.deb"
    powerai_playbook:
        description: Playbook for installing Power machine learning frameworks
        mldl_deb: "packages/mldl.deb"


switches:
    mgmt:
    -   hostname: mgmtswitch1
        ipv4-addr: 192.168.0.5
        rack-id: rack1
        userid: admin
        password: admin
    data:
    -   hostname: dataswitch1
        ipv4-addr: 9.3.89.24
        rack-id: rack1
        userid: admin
        password: admin
nodes:
    deeplearning:
    -   hostname: deeplearning-1
        powerai-frameworks: 
        - caffe-nv
        - caffe-bvlc
        - caffe-ibm
        - digits
        userid-ipmi: ADMIN
        password-ipmi: ADMIN
        port-ipmi: 5
        port-pxe: 6
        port-eth10: 35
        port-eth11: 59/2
        mac-ipmi: 0c:c4:7a:4d:86:aa
        ipv4-ipmi: 192.168.0.101
        mac-pxe: 14:63:08:00:16:b3
        ipv4-pxe: 172.17.0.7
        rack-id: rack1
        template: compute
        chassis-part-number: CSE-938BH-R1620BP
        chassis-serial-number: C9380AE15AH0247
        model: SYS-5038ML-H8TRF
        serial-number: S13656825718481
        external0-addr: 9.3.102.13
        external1-addr: ''
        external2-addr: ''
        mac-eth10: 7c:fe:90:a5:36:10
        mac-eth11: 7c:fe:90:a5:36:20
        bond0-addr: 192.168.1.3




ipaddr-mgmt-network: 192.168.0.0/24
ipaddr-mgmt-switch:
    rack1: 192.168.0.5
ipaddr-data-switch:
    rack1: 9.3.89.24
redundant-network: false
userid-default: ubuntu
password-default: passw0rd
userid-mgmt-switch: admin
password-mgmt-switch: admin
userid-data-switch: admin
password-data-switch: admin
internal-floating-ipaddr: 9.3.89.55
external-floating-ipaddr: 9.3.89.56
networks:
    external0:
        description: Organization site or external network
        addr: 9.3.102.0/24
        broadcast: 9.3.102.255
        gateway: 9.3.102.1
        dns-nameservers: 9.3.1.200
        dns-search: aus.stglabs.ibm.com
        method: static
        eth-port: eth15
    external1:
        description: Interface for eth10
        method: manual
        eth-port: eth10
    external2:
        description: Interface for eth11
        method: manual
        eth-port: eth11

    bond0:
        description: Multilink bond
        bond: mybond1
        addr: 192.168.1.0/24
        broadcast: 192.168.1.255
        method: static
        mtu: 9000
        #name of physical interfaces to bond together.
        bond-interfaces:
            - eth10
            - eth11
        #if necessary not all bond modes support a primary slave
        bond-primary: eth10
        #bond-mode, needs to be one of 7 types
        # either name or number can be used.
        #0 balance-rr
        #1 active-backup
        #2 balance-xor
        #3 broadcast
        #4 802.3ad
        #5 balance-tlb
        #6 balance-alb
        #bond-mode: active-backup
        bond-mode: 4
        #there is a long list of optional bond arguments.
        #Specify them here and they will be added to end of bond definition
        optional-bond-arguments:
            bond-miimon: 100
            bond-lacp-rate: 1
            bond-xmit_hash_policy: layer3+4

    openstack-mgmt:
        description: OpenStack Management Network
        bridge: br-mgmt
        method: static
        tcp_segmentation_offload: false
        addr: 172.29.236.0/22
        vlan: 210
        eth-port: eth10
        mtu: 8000
    openstack-stg:
        description: OpenStack Management Network
        bridge: br-storage
        method: static
        tcp_segmentation_offload: false
        addr: 172.29.244.0/22
        vlan: 220
        eth-port: eth10
    openstack-tenant-vxlan:
        description: OpenStack Tenant vxlan Network
        bridge: br-vxlan
        method: static
        addr: 172.29.240.0/22
        vlan: 230
        eth-port: eth11
    openstack-tenant-vlan:
        description: OpenStack Tenant vlan Network
        bridge: br-vlan
        method: static
        addr: 0.0.0.0/1
        eth-port: eth11
    test-bridge-veth:
        description: Test out eth12 veth pairing
        bridge: br-vlan
        method: static
        bridge-port: veth12
        eth-port: eth12
    ceph-replication:
        description: Ceph Replication vlan Network
        addr: 172.29.248.0/22
        bridge: br-replication
        method: static
        vlan: 240
        eth-port: eth11

node-templates:
    compute:
        hostname: compute
        userid-ipmi: ADMIN
        password-ipmi: admin
        cobbler-profile: ubuntu-14.04.4-server-ppc64el
        os-disk: /dev/sdl
        name-interfaces:
            mac-pxe: eth15
            mac-eth10: eth10
            mac-eth11: eth11
        ports:
            pxe:
                rack1:
                - 12
            ipmi:
                rack1:
                - 10
            eth10:
                rack1:
                - 10
            eth11:
                rack1:
                - 27
        networks:
        - external0
        - external1
        - external2
        - bond0
