---
# Copyright 2016, IBM US, Inc.
#
#tensor_dist_install:

#- name: Install ccl driver
#  include: tasks/install_ccl.yml
#  when: "{{ 'caffe-nv' in hostvars[inventory_hostname]['powerai_frameworks'] }}"
- name: ensure tensorflow samples dir exists 
  file: path=/opt/DL/tensorflow/samples state=directory

- name: copy samples directory
  copy: 
    src: "{{ reference_architecture['powerai_playbook']['samples_src'] }}"
    dest: "{{ reference_architecture['powerai_playbook']['samples_dest'] }}"
    mode: 0777

- name: install git
  shell: apt-get install -y git

- name: copy models repo to tensorflow samples
  git:
    repo: "{{ reference_architecture['powerai_playbook']['models_tree'] }}"
    dest: "/data/models"
  when: "groups.{{ nfs.nfs_server }} is defined and inventory_hostname in groups.{{ nfs.nfs_server }}"

- name: tensorflow
  include: tasks/create_dist_driver.yml
  become: true

- name: install openjdk for bazel build
  shell: apt-get install openjdk-8-jdk

- name: add tensorflow-activate to .profile
  lineinfile:
    dest: "/home/{{ userid_default }}/.profile"
    line: "source /opt/DL/tensorflow/bin/tensorflow-activate"
    insertafter: EOF

- name: add bazel-activate to .profile
  lineinfile:
    dest: "/home/{{ userid_default }}/.profile"
    line: "source /opt/DL/bazel/bin/bazel-activate"
    insertafter: EOF
